EhimeEventCalendar/ViewModels/HomeViewModels.cs
using EhimeEventCalendar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EhimeEventCalendar.ViewModels
{
    public class HomeIndexViewModel
    {
        public List<EventInfo> EventInfos { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Days { get; set; }
        public DateTime PrevMonth { get; set; }
        public DateTime NextMonth { get; set; }

    }
}

EhimeEventCalendar/Controllers/EventInfosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EhimeEventCalendar.Exteisions;
using EhimeEventCalendar.Models;
using EhimeEventCalendar.ViewModels;

namespace EhimeEventCalendar.Controllers
{
    public class EventInfosController : Controller
    {
        private AppDbContext db = new AppDbContext();

        [Route("Calendar/{year}/{month}", Name = "CalendarRoute")]
        public ActionResult Calendar(int year, int month)
        {
            var start = new DateTime(year, month, 1, 0, 0, 0);
            var model = new HomeIndexViewModel()
            {
                Year = year,
                Month = month,
                Days = start.AddMonths(1).AddDays(-1).Day,
                PrevMonth = start.AddMonths(-1),
                NextMonth = start.AddMonths(1),
            };
            var end = start.AddMonths(1);
            model.EventInfos = db.EventInfos.Where(x => x.StartTime >= start && x.StartTime < end)
                .OrderBy(x => x.StartTime).ToList();

            return View("../Home/Index", model);
        }

        // GET: EventInfos
        public async Task<ActionResult> Index()
        {
            return View(await db.EventInfos.ToListAsync());
        }

        // GET: Event/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventInfo eventInfo = await db.EventInfos.FindAsync(id);
            if (eventInfo == null)
            {
                return HttpNotFound();
            }
            return View(eventInfo);
        }

        // GET: EventInfos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EventInfos/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、http://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,Url,TimeStamp,Contents,Venue")] EventInfo eventInfo,
            [ModelBinder(typeof(DateTimeBinder))]DateTime startTime,
            [ModelBinder(typeof(DateTimeBinder))]DateTime endTime
            )
        {
            if (ModelState.IsValid)
            {
                eventInfo.StartTime = startTime;
                eventInfo.EndTime = endTime;

                db.EventInfos.Add(eventInfo);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(eventInfo);
        }

        // GET: EventInfos/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventInfo eventInfo = await db.EventInfos.FindAsync(id);
            if (eventInfo == null)
            {
                return HttpNotFound();
            }
            return View(eventInfo);
        }

        // POST: EventInfos/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、http://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,Url,TimeStamp,Contents,Venue")] EventInfo eventInfo,
            [ModelBinder(typeof(DateTimeBinder))]DateTime startTime,
            [ModelBinder(typeof(DateTimeBinder))]DateTime endTime
           )
        {
            if (ModelState.IsValid)
            {
                eventInfo.StartTime = startTime;
                eventInfo.EndTime = endTime;

                db.Entry(eventInfo).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(eventInfo);
        }

        // GET: EventInfos/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventInfo eventInfo = await db.EventInfos.FindAsync(id);
            if (eventInfo == null)
            {
                return HttpNotFound();
            }
            return View(eventInfo);
        }

        // POST: EventInfos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            EventInfo eventInfo = await db.EventInfos.FindAsync(id);
            db.EventInfos.Remove(eventInfo);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EhimeEventCalendar/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EhimeEventCalendar.Models;
using EhimeEventCalendar.ViewModels;

namespace EhimeEventCalendar.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var db = new AppDbContext();
            var start = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1, 0, 0, 0);
            var model = new HomeIndexViewModel()
            {
                Year = DateTime.Now.Year,
                Month = DateTime.Now.Month,
                Days = start.AddMonths(1).AddDays(-1).Day,
                PrevMonth = start.AddMonths(-1),
                NextMonth = start.AddMonths(1),
            };
            var end = start.AddMonths(1);
            // 当月のイベント
            model.EventInfos = db.EventInfos.Where(x => x.StartTime >= start && x.StartTime < end)
                .OrderBy(x=>x.StartTime).ToList();

            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

EhimeEventCalendar/Views/Home/About.cshtml
@{
    ViewBag.Title = "愛媛イベントカレンダーについて";
}
<h2>@ViewBag.Title.</h2>

<h3>コンセプトは「みんなでつくろう」</h3>
<p>
    イベントのまとめサイトで、「ここには載ってないけど、こんなイベントあるのに…」という時、
    自分でイベントを登録できれば他の訪問者やイベント主催者に貢献することができますよね。
</p>

<h3>告知サイトからの取り込み</h3>
<p>
    一から情報を登録するのは大変なので、
    イベントの告知サイトからイベントの情報を取り込み（参照）できるようにしています。
    イベント登録画面にて、イベントURLを入力後、「イベント情報を取得」を行ってください。
</p>

対応しているサービス
<ul>
    <li><a href="http://atnd.org/" target="_blank">ATND</a></li>
    <li><a href="http://connpass.com/" target="_blank">conpass</a></li>
    <li><a href="http://www.doorkeeper.jp/" target="_blank">Doorkeeper</a></li>
    <li><a href="http://www.zusaar.com/" target="_blank">Zusaar</a></li>
</ul>

EhimeEventCalendar/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "連絡先";
}
<h2>@ViewBag.Title.</h2>

ご要望や苦情はこちらまでお願いします。

<address>
    twitter : <a href="http://twitter.com/nakaji" target="_blank">@@nakaji</a><br />
    GitHub : <a href="https://github.com/nakaji" target="_blank">nakaji</a><br />
</address>

EhimeEventCalendar/Views/Home/Index.cshtml
@model EhimeEventCalendar.ViewModels.HomeIndexViewModel

@{
    ViewBag.Title = "愛媛イベントカレンダー(alpha)";
}

<div class="jumbotron">
    <h1>@ViewBag.Title</h1>
    <p class="lead">
        愛媛のイベントをみんなで登録・共有しよう。
    </p>
</div>

<div class="row">
    <div class="col-md-12">
        <h2 id="ym">@Model.Year 年 @Model.Month 月のイベント</h2>
        <div class="row">
            @Html.ActionLink("<< 前月", "Calendar", "EventInfos", new { year = Model.PrevMonth.Year, month = Model.PrevMonth.Month }, new { @class = "btn btn-default" })
            @Html.ActionLink("翌月 >>", "Calendar", "EventInfos", new { year = Model.NextMonth.Year, month = Model.NextMonth.Month }, new { @class = "btn btn-default pull-right" })
        </div>
        <table class="table">
            <thead>
                <tr>
                    <td>日付</td>
                    <td>タイトル</td>
                    <td>時刻</td>
                </tr>
            </thead>
            <tbody>
                @for (var i = 1; i <= Model.Days; i++)
                {
                    var events = Model.EventInfos.Where(x => x.StartTime.Day == i).ToList();
                    if (events.Any())
                    {
                        <tr>
                            <td rowspan="@events.Count().ToString()">@i</td>
                            <td>@Html.ActionLink(events.First().Title, "Details", "EventInfos", new { id = events.First().Id }, null)</td>
                            <td>@events.First().StartTime.ToString("HH:mm")～@events.First().EndTime.ToString("HH:mm")</td>
                        </tr>
                        if (events.Count > 1)
                        {
                            foreach (var e in events.Skip(1))
                            {
                                <tr>
                                    <td>@Html.ActionLink(e.Title, "Details", "EventInfos", new { id = e.Id }, null)</td>
                                    <td>@events.First().StartTime.ToString("HH:mm")～@events.First().EndTime.ToString("HH:mm")</td>
                                </tr>
                            }
                        }

                    }
                    //イベントがない日は表示しない
                    @*else
                        {
                            <tr>
                                <td>@i</td>
                                <td></td>
                            </tr>
                        }*@
                }
            </tbody>
        </table>
    </div>
</div>

<div id="fb-root"></div>
<div>
    <ul class="snsb">
        <li><a class="twitter-share-button" href="https://twitter.com/share">Tweet</a></li>
        <li><div class="fb-like" data-href="http://ehime-events.azurewebsites.net/" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div></li>
    </ul>
</div>

@section scripts
{
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.0";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    <script type="text/javascript">
        window.twttr = (function (d, s, id) { var t, js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) { return } js = d.createElement(s); js.id = id; js.src = "https://platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs); return window.twttr || (t = { _e: [], ready: function (f) { t._e.push(f) } }) }(document, "script", "twitter-wjs"));
    </script>
}